name: Build and Deploy Personal Website
on: [push, pull_request]
jobs:
  build_deploy_next:
    name: Build and Deploy Next
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn lint

      - name: Build website
        run: yarn build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/website/out


  build_jekyll:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt install ruby ruby-dev ruby-bundler
          cd packages/legacy && make install
      - name: Build the site
        run: |
          echo "Building version $GIT_HASH"
          cd packages/legacy && make build
        env: # Export secret as an environment variable
          GOOGLE_ANALYTICS_GTAG: ${{ secrets.GOOGLE_ANALYTICS_GTAG }}
          PAGES_REPO_NWO: ${{ github.repository }}
          GIT_HASH: ${{ github.sha }}
